# Generated by Django 4.1.5 on 2023-04-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('state', models.TextField(choices=[('Maharashtra', 'Maharashtra')], default='Maharashtra')),
                ('city', models.TextField(choices=[('Mumbai', 'Mumbai')], default='Mumbai')),
                ('pincode', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('warehousename', models.TextField(max_length=20)),
                ('state', models.TextField(choices=[('Maharashtra', 'Maharashtra')], default='Maharashtra')),
                ('city', models.TextField(choices=[('Mumbai', 'Mumbai')], default='Mumbai')),
                ('pincode', models.IntegerField()),
                ('lenght', models.IntegerField()),
                ('bredth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('area', models.IntegerField()),
                ('images', models.ImageField(upload_to='images')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('goodname', models.TextField(max_length=20)),
                ('lenght', models.IntegerField()),
                ('bredth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('area', models.IntegerField()),
                ('images', models.ImageField(upload_to='images')),
                ('date', models.DateField()),
                ('warehousename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.warehouse')),
            ],
        ),
    ]
