# Generated by Django 4.1.5 on 2023-10-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_good_abc_alter_good_warehousename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='abc',
        ),
    ]
